### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by Jeontaeyun** [Jeontaeyun/personal-blog-front#12]
- [ ] Implement the Google, Kakao, GitHub login button
- [ ] Implement the local login button
- [ ] Implement login and register switching featrue
- [ ] Implement the api call with Oauth2.0 and Local auth
- [ ] Implement the responsible view
- [ ] Implement regex with email and password
